---
- id: 1
  name: servers
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-07-01 18:47:10.712586000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2019-07-01 14:47:10.712586000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2019-07-01 18:47:10.712586000 Z
    zone: *1
    time: 2019-07-01 14:47:10.712586000 Z
